version: '3.4'

# 本文件 用作 Release 用，用作 Docker 部署

services:
  afdian-server.service:
    image: yiyungent/afdian-server
    container_name: afdian-server-container
    ports:
      - "1207:80"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_ENVIRONMENT=Production
      # 注意：http://*:80 不要用 双引号 "" 引起来
      - ASPNETCORE_URLS=http://*:80
    volumes:
      # 注意: Linux 下 区分大小写
      - ./appsettings.json:/app/appsettings.json
